name: Deploy to GitHub Pages 2

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IL_TELEFONO: ${{ vars.IL_TELEFONO }}
      LA_CHIAVE_API: ${{ vars.LA_CHIAVE_API }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create public directory
      run: mkdir -p public

    - name: Print variables
      run: |
        echo "Telefono: $IL_TELEFONO"
        echo "Chiave API: $LA_CHIAVE_API"

    - name: Create HTML file with secrets
      run: |
        echo "il_telefono=${{vars.IL_TELEFONO}}" >> $GITHUB_OUTPUT
        echo ${{env.il_telefono}}
        echo "<!DOCTYPE html>
        <html lang='en'>
        <head>
          <meta charset='UTF-8'>
          <meta name='viewport' content='width=device-width, initial-scale=1.0'>
          <title>Secrets</title>
        </head>
        <body>
          <h1>Variables</h1>
          <p>Telefono: ${{env.il_telefono}}</p>
          <p>Chiave API: $LA_CHIAVE_API</p>
        </body>
        </html>" > public/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
