name: Deploy to GitHub Pages 2

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
permissions:
  contents: write  # Garantisce che il token abbia i permessi necessari
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create HTML file with secrets
      run: |
        echo "<!DOCTYPE html>
        <html lang='en'>
        <head>
          <meta charset='UTF-8'>
          <meta name='viewport' content='width=device-width, initial-scale=1.0'>
          <title>Secrets</title>
        </head>
        <body>
          <h1>Secrets</h1>
          <p>Telefono: ${IL_TELEFONO}</p>
          <p>Chiave API: ${LA_CHIAVE_API}</p>
        </body>
        </html>" > public/index.html
      env:
        IL_TELEFONO: ${{ secrets.IL_TELEFONO }}
        LA_CHIAVE_API: ${{ secrets.LA_CHIAVE_API }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
